import unittest

from boolean import Boolean
from typing import Callable, List, Any


class TestBoolean(unittest.TestCase): 
    def __check(self, er: Exception, func: Callable, types: List[Any]) -> None:
        for t in types:
            self.assertRaises(er, func, t)


    def test_boolean_constructor(self) -> None:
        self.__check(TypeError, Boolean,  [None, 1.0, 3+4j, [], (), {}, 1])
    

    def test_boolean_value(self) -> None: ...
    def test_compare_to(self) -> None: ...
    def test_to_string(self) -> None: ...
    def test_hash_code(self) -> None: ...

    def test_compare(self) -> None: ...
    def test_get_boolean(self) -> None: ...
    def test_hash_code(self) -> None: ...
    def test_logical_and(self) -> None: ...
    def test_logical_or(self) -> None: ...
    def test_logical_xor(self) -> None: ...
    def test_parse_boolean(self) -> None: ...
    def test_to_string(self) -> None: ...


if __name__ == '__main__':
    unittest.main()
