import unittest

from .integer import Integer

# добавлю позже

class TestInteger(unittest.TestCase):
    def test_float_value(self) -> None: ...
    def test_get_hash_code(self) -> None: ...
    def test_to_string(self) -> None: ...
    def test_to_bin(self) -> None: ...
    def test_to_hex(self) -> None: ...

    def test_parse_int(self) -> None: ...
    def test_min(self) -> None: ...
    def test_max(self) -> None: ...
    def test_sum(self) -> None: ...
    def test_bit_count(self) -> None: ...
    def test_compare(self) -> None: ...
    def test_to_binary(self) -> None: ...


if __name__ == '__main__':
    unittest.main()